### ISSUE TITLE
RDA1: Research Wire framing App

### ISSUE THREAD

**Issue by Justinfan827** [rice-apps/RiceDeliveryApp#15]
See if you can find something that's specific to React Native IOS and can be a 'live' wireframe

**Comment by willsu88** [comment]
*Imitating Snapchat's app interface

![img_5802](https://user-images.githubusercontent.com/31869979/45921597-5d94f500-be7e-11e8-92fb-72ec6d7ec39a.JPG)

**Comment by willsu88** [comment]
*Imitating Snapchat's interface

![vendor side](https://user-images.githubusercontent.com/31869979/45921617-8321fe80-be7e-11e8-8ad5-9dd5b8886fe8.JPG)

**Comment by willsu88** [comment]
*Imitating Snapchat's interface
![vendor side](https://user-images.githubusercontent.com/31869979/45921625-ab116200-be7e-11e8-8d2c-703fef80b357.JPG)

**Comment by willsu88** [comment]
*End-User Interface
![end-user](https://user-images.githubusercontent.com/31869979/45921641-eca20d00-be7e-11e8-8ce2-ff1927e2d482.JPG)
