### ISSUE TITLE
Write out the steps and create a demo showcasing the process of navigating from one page to another, going back one page, and storing the history of navigation in the MobX store.

### ISSUE THREAD

**Issue by TheWillMundy** [rice-apps/RiceDeliveryApp#34]

**Comment by amyhuyen98** [comment]
[Navigation Step By Step.pdf](https://github.com/rice-apps/RiceDeliveryApp/files/2458996/Navigation.Step.By.Step.pdf)

**Comment by amyhuyen98** [comment]
Updated Navigation Step By Step
[Navigation Step By Step V2.pdf](https://github.com/rice-apps/RiceDeliveryApp/files/2463220/Navigation.Step.By.Step.V2.pdf)
